config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#index'
  resources :customers, only: [:index, :show, :update]
  get "angular_test", to: "angular_test#index"
  get "fake_billing", to: "fake_billing#show"
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :state
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/customer_detail.rb
class CustomerDetail < ActiveRecord::Base
  self.primary_key = 'customer_id'

  def update(params)
    Customer.find(self.customer_id).update(params.permit(:first_name, :last_name, :username, :email))
    Address.find(self.billing_address_id).update(address_attributes(params, "billing"))
    Address.find(self.shipping_address_id).update(address_attributes(params, "shipping"))
  end

  private

    def address_attributes(params, type)
      {
        street: params["#{type}_street"],
        city: params["#{type}_city"],
        state: State.find_by_code(params["#{type}_state"]),
        zipcode: params["#{type}_zipcode"],
      }
    end
end

app/models/customer_search_term.rb
class CustomerSearchTerm
  attr_reader :where_clause, :where_args, :order
  def initialize(search_term)
    search_term = search_term.downcase
    @where_clause = ""
    @where_args = {}
    if search_term =~ /@/
      build_for_email_search(search_term)
    else
      build_for_name_search(search_term)
    end
  end


private

  def build_for_email_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name] = starts_with(extract_name(search_term))

    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(extract_name(search_term))

    @where_clause << " OR #{case_insensitive_search(:email)}"
    @where_args[:email] = search_term

    @order = "lower(email) = " + 
      ActiveRecord::Base.connection.quote(search_term) + 
      " desc, last_name asc"
  end

  def extract_name(email)
    email.gsub(/@.*$/,'').gsub(/[0-9]+/,'')
  end

  def build_for_name_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name]  = starts_with(search_term)

    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(search_term)

    @order = "last_name asc"
  end

  def starts_with(search_term)
    search_term + "%"
  end

  def case_insensitive_search(field_name)
    "lower(#{field_name}) like :#{field_name}"
  end
end

app/models/customers_billing_address.rb
class CustomersBillingAddress < ActiveRecord::Base
  belongs_to :address
  belongs_to :customer
end

app/models/customers_shipping_address.rb
class CustomersShippingAddress < ActiveRecord::Base
  belongs_to :address
  belongs_to :customer
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :addresses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/angular_test_controller.rb
class AngularTestController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_action :authenticate_user!

  protected

    def json_request?
      request.format.json?
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  PAGE_SIZE = 10

  def index
    @page = (params[:page] || 0).to_i
    if params[:keywords].present?
      @keywords = params[:keywords]
      customer_search_term = CustomerSearchTerm.new(@keywords)
      @customers = Customer.where(
          customer_search_term.where_clause, 
          customer_search_term.where_args).
        order(customer_search_term.order).
        offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    else
      @customers = []
    end
    respond_to do |format|
      format.html {}
      format.json { render json: @customers }
    end
  end

  def show
    customer_detail = CustomerDetail.find(params[:id])
    respond_to do |format|
      format.json { render json: customer_detail}
    end
  end

  def update
    customer_detail = CustomerDetail.find(params[:id])
    customer_detail.update(params)
    head :ok
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/fake_billing_controller.rb
class FakeBillingController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    if params[:cardholder_id]
      sleep 2
      render json: {
        lastFour: Faker::Business.credit_card_number[-4..-1],
        cardType: Faker::Business.credit_card_type,
        expirationMonth: Faker::Business.credit_card_expiry_date.month,
        expirationYear: Faker::Business.credit_card_expiry_date.year,
        detailsLink: Faker::Internet.url
      }
    else
      head :not_found
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/angular_test/index.html.erb
<article ng-app="angular_test">
  <header>
    <h1 ng-if="name">Hello, {{name}}</h1>
  </header>
  <section>
    <form class="form-inline">
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" 
               name="name"
               type="text" 
               placeholder="Enter your name" 
               autofocus 
               ng-model="name">
      </div>
    </form>
  </section>
</article>

app/views/customers/_pager.html.erb
<nav>
  <ul class="pager">
    <li class="previous">
      <a href="" ng-click="previousPage()">&larr;Previous</a>
    </li>
    <li class="next">
      <a href="" ng-click="nextPage()">Next &rarr;</a>
    </li>
  </ul>
</nav>

app/views/customers/index.html.erb
<article ng-app="customers" >
  <div ng-view></div>
</article>

app/views/dashboard/index.html.erb
<header>
  <h1>
    Welcome to Shine, <%= current_user.email %>
  </h1>
  <h2>
    We're using Rails <%= Rails.version %>
  </h2>
</header>
<section>
  <ul>
    <li><%= link_to "Customer Search", customers_path %></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shine</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  <% if notice.present? %>
    <aside class="alert alert-info">
      <%= notice %>
    </aside>
  <% end %>
  <% if alert.present? %>
    <aside class="alert alert-danger">
      <%= alert %>
    </aside>
  <% end %>

<%= yield %>

</body>
</html>